# Generated by Django 5.0.1 on 2024-03-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_desc_alter_category_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='images',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
